version: "2.1"

volumes:
  proxy:
  certs:
  db:

services:
  # https://hub.docker.com/r/jc21/nginx-proxy-manager/
  proxy:
    build: proxy
    network_mode: host
    volumes:
      - proxy:/data
      - certs:/etc/letsencrypt
    depends_on:
      - db

  # https://hub.docker.com/_/mariadb/
  db:
    build: mariadb
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    ports:
      - "3306:3306"
